repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: "black ."
        types: [python]
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]
      - id: pyright
        name: pyright
        language: system
        entry: pyright
        types: [python]
